/* Security.vcl breach2vcl config VCL
 * Copyright (C) 2009 Kacper Wysocki
 * 
 * the rules enabled here are auto-generated by ../tools/all2vcl.pl
 */

include "/etc/varnish/security/breach/20_protocol_violations.vcl";
include "/etc/varnish/security/breach/21_protocol_anomalies.vcl";
include "/etc/varnish/security/breach/23_request_limits.vcl";
include "/etc/varnish/security/breach/30_http_policy.vcl";
include "/etc/varnish/security/breach/35_bad_robots.vcl";
include "/etc/varnish/security/breach/40_generic_attacks.vcl";
include "/etc/varnish/security/breach/45_trojans.vcl";
include "/etc/varnish/security/breach/50_outbound.vcl";
